// Package keyring holds the data keys pastes are encrypted with.
//
// Each data key is generated by rypt (wrap), stored only in wrapped form in
// rqlite, and unwrapped once at startup, so creating or reading a paste never
// calls rypt. Pastes are sealed locally with AES-256-GCM. The newest data key
// seals new pastes; older ones are kept to open pastes made before a rotation.
package keyring

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/x6c-co/p-x6c-us/internal/store"
)

// Wrapper is the part of the rypt client the keyring needs.
type Wrapper interface {
	Wrap(ctx context.Context, aad []byte) (dek, wrapped []byte, err error)
	Unwrap(ctx context.Context, wrapped, aad []byte) ([]byte, error)
}

// Store is the part of store.Store the keyring needs.
type Store interface {
	DataKeys(ctx context.Context) ([]store.DataKey, error)
	AddDataKey(ctx context.Context, k store.DataKey) error
}

var ErrUnknownKey = errors.New("paste was sealed under an unknown data key")

type Ring struct {
	active string
	aeads  map[string]cipher.AEAD
}

// Load unwraps every stored data key, generating the first one through rypt
// if there are none yet. It costs one rypt operation per stored key.
func Load(ctx context.Context, st Store, w Wrapper) (*Ring, error) {
	keys, err := st.DataKeys(ctx)
	if err != nil {
		return nil, fmt.Errorf("loading data keys: %w", err)
	}
	known := map[string][]byte{}
	if len(keys) == 0 {
		k, dek, err := newKey(ctx, w)
		if err != nil {
			return nil, err
		}
		if err := st.AddDataKey(ctx, k); err != nil {
			return nil, fmt.Errorf("storing first data key: %w", err)
		}
		known[k.ID] = dek
		// Re-read rather than use k alone: another replica starting at the
		// same moment may have stored a key too, and every replica must be
		// able to open every paste.
		if keys, err = st.DataKeys(ctx); err != nil {
			return nil, fmt.Errorf("loading data keys: %w", err)
		}
	}

	r := &Ring{aeads: make(map[string]cipher.AEAD, len(keys))}
	for _, k := range keys {
		dek, ok := known[k.ID]
		if !ok {
			if dek, err = w.Unwrap(ctx, k.Wrapped, keyAAD(k.ID)); err != nil {
				return nil, fmt.Errorf("unwrapping data key %s: %w", k.ID, err)
			}
		}
		aead, err := newAEAD(dek)
		if err != nil {
			return nil, fmt.Errorf("data key %s: %w", k.ID, err)
		}
		r.aeads[k.ID] = aead
		r.active = k.ID // keys are oldest first, so this ends on the newest
	}
	return r, nil
}

// Rotate generates a new data key through rypt and stores it. Running
// replicas keep sealing with the old key until they restart; pastes sealed
// under either key stay readable.
func Rotate(ctx context.Context, st Store, w Wrapper) (string, error) {
	k, _, err := newKey(ctx, w)
	if err != nil {
		return "", err
	}
	return k.ID, st.AddDataKey(ctx, k)
}

func newKey(ctx context.Context, w Wrapper) (store.DataKey, []byte, error) {
	id := uuid.NewString()
	dek, wrapped, err := w.Wrap(ctx, keyAAD(id))
	if err != nil {
		return store.DataKey{}, nil, fmt.Errorf("generating data key: %w", err)
	}
	return store.DataKey{ID: id, Wrapped: wrapped, CreatedAt: time.Now()}, dek, nil
}

// Active is the ID of the data key new pastes are sealed with.
func (r *Ring) Active() string { return r.active }

// Seal encrypts plaintext for paste pasteID under the active key. The paste
// ID is bound as additional data, so ciphertext copied to another paste's row
// fails to open.
func (r *Ring) Seal(pasteID string, plaintext []byte) (keyID string, nonce, ciphertext []byte) {
	aead := r.aeads[r.active]
	nonce = make([]byte, aead.NonceSize())
	rand.Read(nonce) // never returns an error since Go 1.24
	return r.active, nonce, aead.Seal(nil, nonce, plaintext, pasteAAD(pasteID))
}

// Open decrypts a paste sealed by Seal.
func (r *Ring) Open(keyID, pasteID string, nonce, ciphertext []byte) ([]byte, error) {
	aead, ok := r.aeads[keyID]
	if !ok {
		return nil, ErrUnknownKey
	}
	if len(nonce) != aead.NonceSize() {
		return nil, fmt.Errorf("nonce is %d bytes, want %d", len(nonce), aead.NonceSize())
	}
	return aead.Open(nil, nonce, ciphertext, pasteAAD(pasteID))
}

func newAEAD(dek []byte) (cipher.AEAD, error) {
	if len(dek) != 32 {
		return nil, fmt.Errorf("key is %d bytes, want 32", len(dek))
	}
	block, err := aes.NewCipher(dek)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// The "p-x6c-us/" prefix keeps these values from matching AAD that anything
// else using the same rypt key might choose.
func keyAAD(keyID string) []byte     { return []byte("p-x6c-us/data-key/" + keyID) }
func pasteAAD(pasteID string) []byte { return []byte("p-x6c-us/paste/" + pasteID) }
